package com.szy.yishopcustomer.ResponseModel.Shop;

/**
 * Created by buqingqiang on 2016/7/28.
 * All Rights Reserved By 秦皇岛商之翼网络科技有限公司.
 */
public class User {
    public String user_id;//"user_id":"5",
    public String user_name;//            "user_name":"鞋柜自营旗舰店店长",
    public String mobile;//"mobile":"13245678949",
    public String email;//"email":"13245678409@qq.com",
    public String is_seller;//        "is_seller":"1",
    public String shop_id;//"shop_id":"4",
    public String password;//"password":"$2y$13$FJYgZWTaPS0wfCKuk.ny4u/scZzLS3yMKM44ksp0RPNk0FS0RcPqW",
    public String password_reset_token;//"password_reset_token":"",
    public String salt;//"salt":"",
    public String nickname;//"nickname":"鞋柜自营",
    public String sex;//"sex":"0",
    public String birthday;//"birthday":"989856000",
    public String address_now;//"address_now":"13,03,02",
    public String detail_address;//"detail_address":"",
    public String headimg;//"headimg":null,
    public String user_money;//"user_money":"100000.00",
    public String user_money_limit;//"user_money_limit":"98903.00",
    public String frozen_money;//"frozen_money":"100000.00",
    public String pay_point;//"pay_point":"0",
    public String rank_point;//"rank_point":"0",
    public String address_id;//"address_id":"33",
    public String rank_id;//"rank_id":"1",
    public String mobile_validated;//"mobile_validated":"1",
    public String email_validated;//"email_validated":"1",
    public String reg_time;//"reg_time":"1465301023",
    public String reg_ip;//"reg_ip":"192.168.1.53",
    public String last_time;//"last_time":"1469606791",
    public String last_ip;//"last_ip":"192.168.1.115",
    public String visit_count;//"visit_count":"44",
    public String mobile_supplier;//"mobile_supplier":"联通 ",
    public String mobile_province;//"mobile_province":"浙江 ",
    public String mobile_city;//"mobile_city":"宁波 ",
    public String reg_from;//"reg_from":"5",
    public String surplus_password;//"surplus_password":null,
    public String status;//        "status":"1",
    public String auth_key;//"auth_key":"8",
    public String type;//            "type":"0",
    public String is_real;//"is_real":"0",
    public String shopping_status;//"shopping_status":"1",
    public String comment_status;//"comment_status":"1",
    public String role_id;//"role_id":"0",
    public String auth_codes;//"auth_codes":"all",
    public String company_name;//"company_name":null,
    public String company_region_code;//"company_region_code":null,
    public String company_address;//"company_address":null,
    public String purpose_type;//"purpose_type":null,
    public String referral_mobile;//"referral_mobile":null,
    public String employees;//"employees":null,
    public String industry;//"industry":null,
    public String nature;//"nature":null,
    public String contact_name;//"contact_name":null,
    public String department;//"department":null,
    public String company_tel;//"company_tel":null,
    public String qq_key;//"qq_key":"",
    public String weibo_key;//"weibo_key":"",
    public String weixin_key;//"weixin_key":""
}
